export const queryKeys = {
  currentUser: ['currentUser'],
  profile: ['profile'],
  recentActivities: ['recentActivities'],
  businesses: (params = {}) => ['businesses', params],
  business: (id) => ['business', id],
  revenues: (params = {}) => ['revenues', params],
  revenue: (id) => ['revenue', id],
  revenueSummary: (params = {}) => ['revenueSummary', params],
  dashboard: (params = {}) => ['dashboard', params],
  dashboardChart: (params = {}) => ['dashboard', 'chart', params],
  dashboardRecentRevenues: (params = {}) => ['dashboard', 'recent-revenues', params],
  reports: (params = {}) => ['reports', params],
  taxReports: (params = {}) => ['taxReports', params],
};
