export const queryKeys = {
  currentUser: ['currentUser'],
  profile: ['profile'],
  recentActivities: ['recentActivities'],
  businesses: (params = {}) => ['businesses', params],
  business: (id) => ['business', id],
  revenues: (params = {}) => ['revenues', params],
  revenue: (id) => ['revenue', id],
  revenueSummary: (params = {}) => ['revenueSummary', params],
  dashboard: (params = {}) => ['dashboard', params],
  dashboardChart: (params = {}) => ['dashboard', 'chart', params],
  dashboardRecentRevenues: (params = {}) => ['dashboard', 'recent-revenues', params],
  adminStats: ['adminStats'],
  adminUsers: (params = {}) => ['adminUsers', params],
  appSettings: ['appSettings'],
  publicRegistrationStatus: ['publicRegistrationStatus'],
};
